tests
ScenarioA

	StatisticalScenario named: #ScenarioA;
		coordinates: (46.16352961038194 @ -1.1302614212036133) 
		-> (46.166851083597415 @ -1.1267745494842527);
		totalNumberOfBuildings: #determinedByMap;
		residencePercentages:{  
			#AppartmentBlockTypeA -> 0.1.
			#AppartmentBlockTypeB -> 0.1.
			#HouseTypeA -> 0.8};
		climateProfile: #AverageMetricsDistribution;
		trendsProfile: #FrenchConsumptionTrends;
		weightsProfile: #UrbanClimateHypothesisA.